version: "2"
services:
  app:
    build: .
    container_name: "ex-app"
    command: "npm run dev"
    volumes:
      - ./app/:/src/app/
      - node_modules:/src/app/node_modules
    ports:
      - "3000:3000"

  mongodb:
    container_name: "ex-mongodb"
    image: mongo:3.4
    ports:
      - "27017:27017"

volumes:
  node_modules:
